# syntax=docker/dockerfile:1

########################################
# Этап 1: builder
########################################
FROM almalinux:9 AS builder

# ИСПРАВЛЕНИЕ 1: Разные теги для разных репозиториев!
ARG PG_BABEL_TAG=BABEL_5_4_0__PG_17_7
ARG EXT_BABEL_TAG=BABEL_5_4_0
ARG CMAKE_VERSION=3.28.3
ARG POSTGIS_VERSION=3.5.1
ARG TDS_FDW_VERSION=2.0.4

# Установка зависимостей
RUN dnf install -y \
    gcc gcc-c++ make flex bison \
    libicu-devel libxml2-devel openssl-devel \
    libuuid-devel readline-devel zlib-devel \
    python3-devel perl-devel \
    wget unzip git pkgconf-pkg-config krb5-devel \
    geos-devel proj-devel gdal-devel \
    json-c-devel protobuf-c-devel sqlite-devel \
    freetds-devel \
    java-17-openjdk java-17-openjdk-devel && \
    dnf clean all && \
    rm -rf /var/cache/dnf

# ИСПРАВЛЕНИЕ 2: Явное указание Java 17 как версии по умолчанию для CMake
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk
ENV PATH="${JAVA_HOME}/bin:${PATH}"

# Проверка версии Java (для уверенности в логах сборки)
RUN java -version

# Установка cmake
WORKDIR /opt
RUN wget -q https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}-linux-x86_64.sh && \
    sh cmake-${CMAKE_VERSION}-linux-x86_64.sh --skip-license --prefix=/usr/local && \
    rm cmake-${CMAKE_VERSION}-linux-x86_64.sh

ENV PATH="/usr/local/bin:${PATH}"

# Клонирование репозиториев (с РАЗНЫМИ тегами)
WORKDIR /build
RUN git clone --depth 1 --branch ${PG_BABEL_TAG} \
        https://github.com/babelfish-for-postgresql/postgresql_modified_for_babelfish.git && \
    git clone --depth 1 --branch ${EXT_BABEL_TAG} \
        https://github.com/babelfish-for-postgresql/babelfish_extensions.git

# Сборка PostgreSQL (без опасных флагов --without-readline/zlib)
WORKDIR /build/postgresql_modified_for_babelfish
RUN ./configure --prefix=/opt/postgres \
        --with-libxml --with-uuid=e2fs --with-icu --with-openssl \
        --with-gssapi --disable-werror && \
    make -j"$(nproc)" && \
    make install && \
    cd contrib && make -j"$(nproc)" && make install

ENV PG_CONFIG=/opt/postgres/bin/pg_config

# Сборка PostGIS
WORKDIR /build
RUN wget -q https://download.osgeo.org/postgis/source/postgis-${POSTGIS_VERSION}.tar.gz && \
    tar -xzf postgis-${POSTGIS_VERSION}.tar.gz && \
    cd postgis-${POSTGIS_VERSION} && \
    ./configure --with-pgconfig=${PG_CONFIG} && \
    make -j"$(nproc)" && make install && \
    cd .. && rm -rf postgis-${POSTGIS_VERSION} postgis-${POSTGIS_VERSION}.tar.gz

# Сборка расширений Babelfish
WORKDIR /build/babelfish_extensions/contrib
RUN cd babelfishpg_money && make -j"$(nproc)" && make install && cd .. && \
    cd babelfishpg_common && \
        PG_CPPFLAGS='-I/usr/include -DENABLE_SPATIAL_TYPES' make -j"$(nproc)" && \
        PG_CPPFLAGS='-I/usr/include -DENABLE_SPATIAL_TYPES' make install && \
        cd .. && \
    cd babelfishpg_tds && make -j"$(nproc)" && make install && cd .. && \
    cd babelfishpg_tsql && \
        PG_CPPFLAGS='-I/usr/include -DENABLE_SPATIAL_TYPES -DENABLE_TDS_LIB' \
        SHLIB_LINK='-lsybdb -L/usr/lib64' \
            make -j"$(nproc)" && \
        PG_CPPFLAGS='-I/usr/include -DENABLE_SPATIAL_TYPES -DENABLE_TDS_LIB' \
        SHLIB_LINK='-lsybdb -L/usr/lib64' \
            make install

########################################
# Этап 2: runtime
########################################
FROM almalinux:9 AS runtime

# Установка зависимостей для runtime
RUN dnf install -y \
    libicu libxml2 openssl libuuid krb5-libs \
    geos proj gdal json-c protobuf-c sqlite-libs \
    freetds glibc-langpack-en shadow-utils && \
    dnf clean all && \
    rm -rf /var/cache/dnf

# Генерация локали
RUN localedef -c -f UTF-8 -i en_US en_US.UTF-8

# Создание пользователя postgres
RUN groupadd -r postgres --gid=26 && \
    useradd -r -g postgres --uid=26 --home-dir=/var/lib/pgsql --shell=/bin/bash postgres && \
    mkdir -p /var/storage/pgsql/data && \
    chown -R postgres:postgres /var/storage/pgsql

# Копирование собранного PostgreSQL
COPY --from=builder /opt/postgres /opt/postgres

ENV PATH="/opt/postgres/bin:${PATH}"
ENV PGDATA=/var/storage/pgsql/data
ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8

# Копирование скриптов
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
COPY healthcheck.sh /usr/local/bin/healthcheck.sh
RUN chmod +x /usr/local/bin/entrypoint.sh /usr/local/bin/healthcheck.sh

VOLUME ["/var/storage/pgsql/data"]
EXPOSE 5432 1433

HEALTHCHECK --interval=30s --timeout=5s --start-period=60s --retries=3 \
    CMD /usr/local/bin/healthcheck.sh

USER postgres
ENTRYPOINT ["entrypoint.sh"]
CMD ["postgres"]
